dist: bionic
env:
  global:
    - LOCAL_IMAGE="graph-notebook"
    - DEV_IMAGE="purpleteam/graph-notebook-dev-ephemeral:$TRAVIS_COMMIT"
    - RELEASE_IMAGE="purpleteam/graph-notebook:${TRAVIS_TAG}"
services:
  - docker
script:
  - docker build -t "graph-notebook:local" .
deploy:
  - provider: script
    skip_cleanup: true
    script: ./script/push_docker.sh "graph-notebook:local" $RELEASE_IMAGE
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./script/push_docker.sh "graph-notebook:local" $DEV_IMAGE
    on:
      all_branches: true
