dist: bionic
env:
  global:
    - DEV_IMAGE_REPOSITORY="graph-notebook-dev-ephemeral/$TRAVIS_COMMIT"
services:
  - docker
script:
  - docker build -t $DEV_IMAGE_REPOSITORY .
deploy:
  provider: script
  script: script/push_docker.sh
  on:
    tags: true
