dist: bionic
env:
  global:
    - LOCAL_IMAGE="graph-notebook:local"
    - DEV_IMAGE="purpleteam/graph-notebook-dev-ephemeral:$TRAVIS_COMMIT"
    - RELEASE_IMAGE="purpleteam/graph-notebook:${TRAVIS_TAG}"
services:
  - docker
script:
  - docker build -t $LOCAL_IMAGE .
deploy:
  - provider: script
    skip_cleanup: true
    script: ./script/push_docker.sh $LOCAL_IMAGE $RELEASE_IMAGE
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./script/push_docker.sh $LOCAL_IMAGE $DEV_IMAGE
    on:
      all_branches: true
